# Autogenerated wrapper script for HelloWorldC_jll for i686-w64-mingw32
export hello_world

JLLWrappers.@declare_executable_product(hello_world)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        hello_world,
        "bin/hello_world.exe",
    )

end  # __init__()
